spring:
  # H2 DB DataSource
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  # Redis DB ??
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info